In [1]:
#리스트를 데이터로 바꾸기

import numpy as np

a = np.array([30,80])
print(a)

print('차원',a.ndim)
print('형태',a.shape)

[30 80]
차원 1
형태 (2,)


In [2]:
#튜플 데이터 만들기

import numpy as np

a = np.array((30,80))
print(a)

print('차원',a.ndim)
print('형태',a.shape)

[30 80]
차원 1
형태 (2,)


In [4]:
# 다차원 numpy 만들기

import numpy as np

a = np.array([[30,80],[80,30]])
print(a)

print('차원',a.ndim)
print('형태',a.shape)

[[30 80]
 [80 30]]
차원 2
형태 (2, 2)


In [5]:
# 2.2.2의 3차원 numpy 배열

import numpy as np

a = np.array([[[30,80],[80,30]],[[40,20],[60,10]]])
print(a)

print('차원',a.ndim)
print('형태',a.shape)

[[[30 80]
  [80 30]]

 [[40 20]
  [60 10]]]
차원 3
형태 (2, 2, 2)


In [7]:
import numpy as np

a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
import numpy as np

a = np.zeros((2,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
import numpy as np

a = np.zeros(((3,6)))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
import numpy as np

a = np.ones((10))
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
import numpy as np

a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
import numpy as np

a = np.arange(0,10,2)
a

a = np.arange(10,20,3)
a

array([10, 13, 16, 19])

In [22]:
import numpy as np

a = np.linspace(0,10,2)
a

a = np.linspace(10,20,3)
a

array([10., 15., 20.])

In [23]:
type(a)

numpy.ndarray

In [24]:
# numpy.ndarray 클래스

In [25]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a.ndim # 차원 값

2

In [32]:
a.shape # 형태

(2, 3)

In [34]:
a.size # 배열 크기

6

In [36]:
a.dtype # 배열 항목의 데이터 타입

dtype('int64')