# **1차원 배열**

In [5]:
# 1차원 배열 생성하기
import numpy as np

ab = np.array([0,1,2,3,4,5,6,7,8,9])
ab

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# 타입 보기
type(ab)

numpy.ndarray

In [20]:
# 차원 보기
ab.ndim

1

In [15]:
# shape 확인
print(ab.shape)

(10,)


In [16]:
# 갯수 확인
len(ab)

10

# **2차원 배열**

In [17]:
# 2차원 배열 생성
c = np.array([[0,1,2],[3,4,5]]) # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
# type 확인
type(c)

numpy.ndarray

In [23]:
# 차원 확인

print(c.ndim)

2


In [19]:
# shape 확인

print(c.shape)

(2, 3)


In [24]:
# 갯수 확인하기

len(c)

2

In [25]:
# 한 1차원의 갯수 확인2

len(c[0])

3

In [26]:
# 전체 갯수 확인

c.size

6

In [27]:
# 전체 갯수 확인

len(c) * len(c[0]) # ien(c) : 행의 갯수 * len(c[0]) : 열의 갯수

6

# **3차원 배열**

In [35]:
# 3차원 배열 생성하기

d = np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]],
              [[11,12,13,14],
              [15,16,17,18],
              [19,20,21,22]]]) # 2 , 3 , 4 array
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [36]:
# shape 확인

d.shape

(2, 3, 4)

In [33]:
# 차원 확인

print(d.ndim)

3


In [37]:
#갯수 확인 ( 2 차원 갯수 확인 )

len(d)

2

In [40]:
# 갯수 확인2 ( 1 차원 갯수 확인 )

len(d[0])

3

In [42]:
# 갯수 확인3 ( 1차원 안의 요소 확인 )

len(d[0][0])

4

In [38]:
# 전체 갯수 보기 (= shape 의 결과를 전부 곱하면 전체 사이즈의 값이 나온다)

d.size

24

# **1차원 배열 인덱싱**

In [44]:
f = np.array([31,52,23,34,42,50])
print(f[4])
print(f[-1])

42
50


# **2차원 배열 인덱싱**

In [45]:
n = np.array([[0,1,2],[3,4,5]])
n

array([[0, 1, 2],
       [3, 4, 5]])

In [46]:
# 첫번째 행의 첫번째 열

n[0,0]

0

In [47]:
# 두번째 행의 세번째 열

n[1,2]

5

In [49]:
# 마지막 행의 마지막 열

n[-1,-1]

5

# **배열 슬라이싱**

In [51]:
g = np.array([[0,1,2],[3,4,5]])
#첫번째 행 전체
g[0,:]

array([0, 1, 2])

In [54]:
# 행 전체에서 열의 인덱스1
g[:,1]

array([1, 4])

In [55]:
# 두번째 행의 두번째 열부터 끝까지

g[1,1:]

array([4, 5])

In [56]:
g[:2,:2]

array([[0, 1],
       [3, 4]])

# **연습 문제**

In [59]:
m = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

1. 이 행렬에서 값 7을 인덱싱한다
2. 이 행렬에서 값 13을 인덱싱한다
3. 이 행렬에서 배열 [6 7 8]을 슬라이싱한다
4. 이 행렬에서 배열 [7 12]를 슬라이싱한다
5. 이 행렬레서 배열 [[3 4] , [8 9]]를 슬라이싱한다

In [66]:
# 1번 답

m[1,2]

7

In [67]:
# 2번 답

m[2,3]

13

In [74]:
# 3번 답 ( 복습 필요 )

m[1:2 , 1:4]

array([[6, 7, 8]])

In [78]:
# 4번 답

m[1: , 2]

array([ 7, 12])

In [80]:
# 5번 답

m[:2 , 3: ]

array([[3, 4],
       [8, 9]])

# **리스트 연산과 배열 연산 차이**

In [81]:
# 리스트 연산 (= 리스트가 하나의 리스트로 합쳐짐)

a = [1,2,3]
b = [4,5,6]

a+b

[1, 2, 3, 4, 5, 6]

In [83]:
# 배열 연산 (= 같은 배열 자리에 )

c = np.array([1,2,3])
b = np.array([4,5,6])

c+b

array([5, 7, 9])