In [ ]:
import numpy as np

### 문자열 타입

*   np.string_
*   데이터가 고정된 크깅의 바이트 매열로 저장
*   python의 일반 str타입이 아니라 btypes의 타입으로 작동
*   저장된 문자열이 고정 길이를 초과하면 자동으로 질림 현상이 발생

In [ ]:
num_strings = np.array(['-3.15','5','8.4','21','-12'],dtype=np.string_)
num_strings.dtype

dtype('S5')

In [ ]:
num_strings02 = num_strings.astype(float)
num_strings02

array([ -3.15,   5.  ,   8.4 ,  21.  , -12.  ])

In [ ]:
num_strings02.dtype

dtype('float64')

### 인덱싱과 슬라이드

In [ ]:
array_1d = np.arange(15)
array_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
array_1d[7]

7

In [ ]:
array_1d[[7,9]]

array([7, 9])

In [ ]:
array_1d[4:7]

array([4, 5, 6])

In [ ]:
array_1d[4:7]=10
array_1d

array([ 0,  1,  2,  3, 10, 10, 10,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
array_2d = np.array([[2,4,6],[3,6,9],[4,8,12]])
array_2d

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [ ]:
array_2d[0]

array([2, 4, 6])

In [ ]:
array_2d[:2]

array([[2, 4, 6],
       [3, 6, 9]])

In [ ]:
array_2d[:2,:2]

array([[2, 4],
       [3, 6]])

In [ ]:
array_2d[[0,1],:2]

array([[2, 4],
       [3, 6]])

In [ ]:
array_2d[:1]

array([[2, 4, 6]])

In [ ]:
array_2d[:,:1]

array([[2],
       [3],
       [4]])

In [ ]:
array_2d[1,2]

9

### 난수 생성하기
- 넘파이의 random모듈은 큰 표본을 생성하면서 빠른 속도를 낸다.
- rand() , randn() , randint()

In [ ]:
np.random.seed(1000)
np.random.rand(5)

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454])

In [ ]:
np.random.rand(5)

array([0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])

In [ ]:
# 표준편차가 1이고 평균값이 0인 정규분포로 실수 난수 생성
np.random.randn(5)

array([ 0.66728131, -0.80611561, -1.19606983, -0.40596016, -0.18237734])

In [ ]:
np.random.randint(5,25,size=10)

array([18, 23, 15, 19, 10, 17, 16, 16,  5, 23])

In [ ]:
np.random.randint(30,size=10)

array([21, 26,  4,  7, 16, 20, 23, 28, 11, 17])

In [ ]:
np.random.randint(5,25,size=(3,3))

array([[ 5, 18, 23],
       [ 6, 16, 19],
       [20, 20, 22]])

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 생성한 데이터 순서 변경
np.random.shuffle(data)
data

array([1, 2, 0, 7, 8, 4, 3, 9, 6, 5])

In [ ]:
# 데이터 무작위 샘플링
np.random.choice(10,5,replace=False)

array([0, 7, 6, 4, 8])

In [ ]:
# replace = True 기본 설정으로 반복을 허용
np.random.choice(10,5,replace=True)

array([8, 4, 1, 0, 9])

In [ ]:
np.random.choice(3,12,p=[0.3,0.7,0])

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1])

In [ ]:
np.random.choice(['banana','apple','orange'],8)

array(['banana', 'orange', 'banana', 'apple', 'banana', 'apple', 'apple',
       'apple'], dtype='<U6')

### numpy 주요 함수
- 통계 , 불리언 , 배열 , 정렬 , 집합

In [ ]:
array = np.random.randint(30,size=20)
array

array([13,  7, 18,  0,  4, 29, 14, 20, 17, 22,  5, 29, 13,  1, 20, 17,  7,
        4, 21, 16])

In [ ]:
# 데이터 길이
len(array)

20

In [ ]:
# 데이터 평균
np.mean(array)

13.85

In [ ]:
# 데이터 중앙값
np.median(array)

15.0

In [ ]:
# 데이터의 표준편차
np.std(array)

8.421846590861175

In [ ]:
# 데이터 표본 분산
np.var(array)

70.9275

In [ ]:
np.max(array)

29

In [ ]:
np.min(array)

0

In [ ]:
np.sum(array)

277

In [ ]:
# 데이터 누적곱 [숫자가 기준값 이상으로 커지면 0으로 반환]
array.cumprod()

array([  13,   91, 1638,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [ ]:
# 데이터 누적합
array.cumsum()

array([ 13,  20,  38,  38,  42,  71,  85, 105, 122, 144, 149, 178, 191,
       192, 212, 229, 236, 240, 261, 277])

In [ ]:
# 사분위수
np.percentile(array,0)

0.0

In [ ]:
np.percentile(array,25)

6.5

In [ ]:
array = np.random.randn(50)
array

array([ 0.10319289,  0.64424261,  0.32807995,  0.85743275, -0.93696928,
        0.18007496, -1.42337059, -0.36775578, -1.52328799, -0.6347717 ,
        0.98740384, -1.01601962,  2.04572375,  0.24999852,  0.65116253,
       -1.26602354,  1.3741556 , -0.60990513,  0.03075795,  0.81965668,
        1.45431373, -0.58367645,  0.41534745,  0.66702578,  0.8694953 ,
       -1.20270333,  2.86176918, -2.68159245, -1.16881176, -0.58416422,
        0.8182497 ,  1.59043723, -0.25828823,  0.44702904,  1.93841974,
       -0.39031935, -0.58069634,  1.94898697, -1.86255134, -0.56835658,
        0.97922403,  0.89536389, -0.23626245,  0.44109793, -0.99241399,
        0.29550499,  0.04215969,  0.76213902,  0.62795647,  0.10712324])

In [ ]:
(array> 0).sum()

30

In [ ]:
bools = np.array([1,1,0,0])
bools

array([1, 1, 0, 0])

In [ ]:
# 불리언 배열에서 데이터 중 1개 이상의 True 값의 존재 여부를 알려줌
bools.any()

True

In [ ]:
# 불리언 배열 데이터 전체가 True 값인지 알려줌 (전부 참이 아닐시 = Flase / 맞을시 = True)
bools.all()

False

In [ ]:
array = np.random.randint(20,size=10)
array

array([ 2, 12, 16,  2,  8, 12,  5,  3, 18, 12])

In [ ]:
array.sort()
array

array([ 2,  2,  3,  5,  8, 12, 12, 12, 16, 18])

In [ ]:
array = array[::-1]
array

array([ 2,  2,  3,  5,  8, 12, 12, 12, 16, 18])

### 집합

In [ ]:
fruits = np.array(['apple','banana','kiwi','apple','kiwi','lemon','banana','lemon'])
fruits

array(['apple', 'banana', 'kiwi', 'apple', 'kiwi', 'lemon', 'banana',
       'lemon'], dtype='<U6')

In [ ]:
# 배열내에서 중복되 값을 모두 제거하고 값 반환
np.unique(fruits)

array(['apple', 'banana', 'kiwi', 'lemon'], dtype='<U6')

In [ ]:
sorted(set(fruits))

['apple', 'banana', 'kiwi', 'lemon']

In [ ]:
n = np.array([1,4,6,9,2,3,5,1])
n1 = np.array([5,7,1,2,1,7,8,5])

In [ ]:
# 배열에 공통으로 존재하는 값 추출
np.intersect1d(n,n1)

array([1, 2, 5])

In [ ]:
np.union1d(n,n1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 문제

In [158]:
import numpy as np
h = np.array([1.82,2.76,1.69,1.86,1.77,1.73])
w = np.array([86,74,59,95,80,68])
b = h/w**2
print('대상 키 : ',h)
print('대상 체충 : ',w)
print('대상 비만도 : ',b)

대상 키 :  [1.82 2.76 1.69 1.86 1.77 1.73]
대상 체충 :  [86 74 59 95 80 68]
대상 비만도 :  [0.00024608 0.00050402 0.00048549 0.00020609 0.00027656 0.00037413]


In [174]:
players = np.array( [ [ 170,76.4 ], [ 183,86.2 ], [ 181,78.5 ], [ 176,80.1 ] ] )
print( "몸무게가 80 이상인 선수 정보 : ", players [ players [ :, 1 ] >= 80 ] )
print( "키가 180 이상인 선수 정보 : ", players [ players[ : , 0 ] >= 180 ] )

몸무게가 80 이상인 선수 정보 :  [[183.   86.2]
 [176.   80.1]]
키가 180 이상인 선수 정보 :  [[183.   86.2]
 [181.   78.5]]


In [184]:
info = np.array([[151.4, 172.45, 138.65, 177.63, 207.46],
                 [44.64, 163.5, 112.35, 73.55, 97.83]])
h = info[0]
w = info[1]
h_j = ( h < 150) | ( h > 195)
w_j = w >= 14
i_j = np.where( h_j | w_j )[0]
result = i_j.append(list)
print(result)

# 이번 문제 좀 틀린거 같은디..

AttributeError: 'numpy.ndarray' object has no attribute 'append'

선생님 오늘도 화이팅하시고</br>
좋은하루 보내세요<br>
수업도중 참고 사이트 : https://jimmy-ai.tistory.com/46