In [ ]:
import numpy as np
numpy.__version__

'1.26.4'

In [ ]:
a = np.array([4,3,2])
a.shape , a.ndim , a.size , a.dtype , a.itemsize

((3,), 1, 3, dtype('int64'), 8, array([4, 3, 2]))

In [ ]:
b = np.array([[2,3,4],[4,5,6]])
b.shape

(2, 3)

# ***numpy 브로드캐스팅***

In [ ]:
c = np.array([10,20,30])
d = np.array([1,2,3])
c+d , c-d , c*d , c/d , c//d ,c%d

(array([11, 22, 33]),
 array([ 9, 18, 27]),
 array([10, 40, 90]),
 array([10., 10., 10.]),
 array([10, 10, 10]),
 array([0, 0, 0]))

# **다차원배열의 브로드캐스팅**

In [ ]:
e = np.array([[10,20,30],[40,50,60]])
f = np.array([2,3,4])
e.shape , f.shape , e, f ,e+f

((2, 3),
 (3,),
 array([[10, 20, 30],
        [40, 50, 60]]),
 array([2, 3, 4]),
 array([[12, 23, 34],
        [42, 53, 64]]))

In [ ]:
e+f , e-f , e*f , e/f , e//f ,e%f

(array([[12, 23, 34],
        [42, 53, 64]]),
 array([[ 8, 17, 26],
        [38, 47, 56]]),
 array([[ 20,  60, 120],
        [ 80, 150, 240]]),
 array([[ 5.        ,  6.66666667,  7.5       ],
        [20.        , 16.66666667, 15.        ]]),
 array([[ 5,  6,  7],
        [20, 16, 15]]),
 array([[0, 2, 2],
        [0, 2, 0]]))

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((2,3),100)

array([[100, 100, 100],
       [100, 100, 100]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [ ]:
np.empty(10)

array([3.39101205e-316, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.39426191e+165, 1.74247934e-076, 5.64163718e-091,
       5.05922731e-038, 4.26050895e-315])

In [ ]:
a1 = np.array([4,5,6,4,5])
a1

array([4, 5, 6, 4, 5])

In [ ]:
a2 = np.zeros_like(a1)
a3 = np.ones_like(a1)
a4 = np.full_like(a1,10)
a4

array([10, 10, 10, 10, 10])

In [ ]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.logspace(0.1,1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

In [ ]:
np.random.randint(0,10,(3,3))

array([[4, 0, 8],
       [8, 8, 2],
       [1, 0, 9]])

In [ ]:
np.random.rand(3,3)

array([[0.47347078, 0.88201929, 0.7406799 ],
       [0.63688107, 0.4513505 , 0.09668768],
       [0.89957512, 0.62973496, 0.71963227]])

In [ ]:
np.zeros(10,dtype=bool)

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [1]:
import numpy as np

In [3]:
np.string_

numpy.bytes_