# 드롭 아웃

In [3]:
# 드롭아웃 없이 Dense 사용하기

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# 모델 정의
model = Sequential([
    Dense(128,activation='relu', input_shape=(100,)),
    Dense(64,activation='relu'),
    Dense(10,activation='softmax')
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , Dropout

model = Sequential([
    Dense(128,activation='relu', input_shape=(100,)),
    Dropout(0.5), # 드랍아웃 비율 50%
    Dense(64,activation='relu'),
    Dropout(0.3), # 드롭아웃 비율 30%
    Dense(10,activation='softmax')
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
import tensorflow as tf

# 범주현 데이터 (문자열 -> 숫자)
# 빨강 = 0 , 파랑 = 1 , 초록 = 2

categories = [0,1,2,0,2]

# 원-핫 인코딩 , depth=3이란 범주의 개수(고유 클래스 수)가 3개
one_hot_encoded = tf.one_hot(categories , depth=3)
print('원-핫 인코딩 결과 :')
print(one_hot_encoded.numpy())

원-핫 인코딩 결과 :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


# 언패킹

In [9]:
fruits = ["사과","바나나","딸기"]

# 언패킹

a,b,c = fruits

print(a)
print(b)
print(c)

사과
바나나
딸기
